version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  
    commands:
      - echo Installing dependencies...
      - npm install  

  pre_build:
    commands:
      - echo No pre-build commands needed.

  build:
    commands:
      - echo No build step needed for this app. It runs directly with Node.js.

  post_build:
    commands:
      - echo Starting the server...
      - npm start 

artifacts:
  files:
    - '**/*'  
    - '!node_modules/**'  

cache:
  paths:
    - 'node_modules/**/*'  
