version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Use the appropriate Node.js version, for example, Node 16
    commands:
      - echo Installing dependencies...
      - npm install  # This installs your project's dependencies (express, socket.io, etc.)

  pre_build:
    commands:
      - echo No pre-build commands needed.

  build:
    commands:
      - echo No build step needed for this app. It runs directly with Node.js.

  post_build:
    commands:
      - echo Starting the server...
      - npm start  # This assumes your package.json has a "start" script to run your server

artifacts:
  files:
    - '**/*'  # Include all files in the project directory
    - '!node_modules/**'  # Exclude node_modules folder from build artifacts

cache:
  paths:
    - 'node_modules/**/*'  # Cache node_modules to speed up future builds
